microblaze: Add TARGET_ASM_OUTPUT_MI_THUNK to support varargs thunk
Without this macro, generic gcc generates a less efficient thunk
that calls function instead of jumping to it. The generic code
does not support varargs and produces an error message on compilation;

 error: generic thunk code fails for method
 'virtual void C::f(const char*, ...)' which uses '...'

Signed-off-by: David Holsgrove <david.holsgrove@petalogix.com>